package db;

import java.sql.Connection;
import java.sql.Statement;

public class DBInitializer {

//    public static void initialize() {
//        try (Connection conn = DBConnection.getConnection();
//             Statement stmt = conn.createStatement()) {
//
//            // Simple example table creation
//            String sql = "CREATE TABLE IF NOT EXISTS SYNC_LOGS (" +
//                    "ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
//                    "SYNC_TYPE VARCHAR2(20), " +
//                    "TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP, " +
//                    "STATUS VARCHAR2(50))";
//
//            stmt.executeUpdate(sql);
//            System.out.println("Database initialized successfully.");
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }
}
